### ISSUE TITLE
Show dot files in the folder manager plugin

### ISSUE THREAD

**Issue by matzipan** [elementary/scratch#111]
At the moment, the file manager never shows dot files, even though some files, such as `.gitignores` or others might be important. 

There should be an option to enable showing them.

**Comment by danrabbit** [comment]
I think in the context of a code editor it doesn't really make sense to hide these files in the first place. Case in point: here on GitHub there is no option, they just always show.

**Comment by matzipan** [comment]
You never see your `.git` folder in other editors, even though you see your `.gitignore`.

**Comment by danrabbit** [comment]
Yeah definitely an edge case. I guess this is because `.git` is assumed to be generated content. Probably could safely hard-code an exception to hide `.git`

**Comment by danrabbit** [comment]
Fixed in #164
