### ISSUE TITLE
Syntax for .fountain files

### ISSUE THREAD

**Issue by TunableRoom9** [elementary/scratch#128]
https://fountain.io/

**Comment by tintou** [comment]
Scratch is based on GtkSourceView, so everything that is working on GEdit is working for us.
Here is a language file found on the internet for fountain http://icnu.narod.ru/soft/fountain.lang
You can just copy it in ~/.local/share/gtksourceview-3.0/language-specs/ and it will work.

**Comment by TunableRoom9** [comment]
Thanks a lot!
