### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by bioglaze** [elementary/scratch#146]
I get a 100 % crash on Loki 0.4.1 with the following repro steps:

1. Start Scratch from the terminal: `scratch-text-editor myfile`
2. Press F3
3. Close the tab that was opened by previous step
4. Press ctrl-s to save
5. Should crash now

Output in terminal for the session during the repro steps:

[INFO 12:36:46.383102] Application.vala:153: Scratch version: 2.4.1
[INFO 12:36:46.383123] Application.vala:155: Kernel version: 4.8.0-58-generic
[DEBUG 12:36:46.387183] Settings.vala:163: Loading settings from schema 'org.pantheon.scratch.saved-state'
[DEBUG 12:36:46.387375] Settings.vala:163: Loading settings from schema 'org.pantheon.scratch.settings'
[DEBUG 12:36:46.387785] Settings.vala:163: Loading settings from schema 'org.pantheon.scratch.services'
[WARNING 12:36:46.396750] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 12:36:46.396776] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 12:36:46.396800] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[DEBUG 12:36:46.407050] [Gtk] Connecting to session manager
[WARNING 12:36:46.410065] [libpeas] Failed to enable unknown plugin loader 'gjs'
[WARNING 12:36:46.411755] [libpeas] Failed to enable unknown plugin loader 'gjs'
[FATAL 12:36:46.468555] [Gtk] gtk_action_set_visible: assertion 'GTK_IS_ACTION (action)' failed
[DEBUG 12:36:46.469461] SplitView.vala:202: WelcomeScreen shown successfully
[DEBUG 12:36:46.471017] Settings.vala:163: Loading settings from schema 'org.pantheon.scratch.plugins.folder-manager'
[DEBUG 12:36:46.472116] SplitView.vala:210: WelcomeScreen hidden successfully
[DEBUG 12:36:46.472566] SplitView.vala:125: View added successfully
[DEBUG 12:36:46.477431] sql-schema.vala:204: schema_version is 10
[DEBUG 12:36:46.492737] Document.vala:747: Could not find mount location
[INFO 12:36:46.492788] Document.vala:167: Opening "New Document"
[DEBUG 12:36:46.541766] sql-schema.vala:204: schema_version is 10
[DEBUG 12:36:46.547914] Document.vala:747: Could not find mount location
[INFO 12:36:46.547957] Document.vala:167: Opening "a"
[DEBUG 12:36:52.914784] SplitView.vala:125: View added successfully
[DEBUG 12:36:52.918726] sql-schema.vala:204: schema_version is 10
[DEBUG 12:36:52.924967] Document.vala:747: Could not find mount location
[INFO 12:36:52.925013] Document.vala:167: Opening "New Document"
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

[INFO 12:36:56.293154] Document.vala:229: Closing "New Document"
[DEBUG 12:36:56.296031] Document.vala:688: Backup file deleting: /home/glaze/.local/share/scratch-text-editor/unsaved/Text file from 2017-07-04 12:36:52~
[DEBUG 12:36:56.296173] Document.vala:692: Backup file doesn't exists: /home/glaze/.local/share/scratch-text-editor/unsaved/Text file from 2017-07-04 12:36:52~
[DEBUG 12:36:56.296270] Document.vala:391: Error when getting information for file '/home/glaze/.local/share/scratch-text-editor/unsaved/Text file from 2017-07-04 12:36:52': No such file or directory
[DEBUG 12:36:56.297308] SplitView.vala:169: View removed successfully
[FATAL 12:36:57.320033] scratch_services_document_get_is_file_temporary: assertion 'self != NULL' failed
Segmentation fault (core dumped)

**Backtrace:**

#0  0x000055555557cee4 in ?? ()
#1  0x000055555556a432 in ?? ()
#2  0x00007ffff5b46fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff5b58fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff5b61d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff5b6208f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff65b41b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff65b4739 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff5b46fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff5b58fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff5b617f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff5b6208f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6607eaf in gtk_accel_group_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff66097dd in gtk_accel_groups_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff6884001 in gtk_window_activate_key () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff6884121 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6722fac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff5b46fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff5b5956e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff5b617f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff5b6208f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff6860c3c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff67204c9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff67221bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff628fd92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007ffff5870197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff58703f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff587049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff6eecd6d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#29 0x00007ffff74b0450 in granite_application_run () from /usr/lib/x86_64-linux-gnu/libgranite.so.3
#30 0x000055555556dfef in scratch_scratch_app_main ()
#31 0x00007ffff547c830 in __libc_start_main (main=0x555555567d50 <main>, argc=1, argv=0x7fffffffdd18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd08) at ../csu/libc-start.c:291
#32 0x0000555555567d89 in _start ()

**Comment by jeremypw** [comment]
Please indicate what version of Scratch (now renamed Code) you were using - I did not reproduce this using the latest vanilla version.  Please also indicate whether you had any plugins active.

**Comment by bioglaze** [comment]
Version is 2.4.1, I don't have any plugins active.

**Comment by jeremypw** [comment]
Ah OK - I can reproduce it now - I was closing the wrong tab. If you close the first opened tab then there is no crash, but if you close the split screen tab it crashes on Ctrl-s.
