### ISSUE TITLE
An unobtrusive status bar to display useful information

### ISSUE THREAD

**Issue by yeboahnanaosei** [elementary/scratch#157]
It would be great for scratch to have a subtle and simple status bar displaying useful information like:
* The current line you are on
* The total number of lines in the file
* The file type and the syntax highlighting
* etc...

**Comment by danrabbit** [comment]
Adding a mockup here. We could make use of the title area to display some project options/status:

![screenshot from 2017-08-20 11 54 54](https://user-images.githubusercontent.com/7277719/29497676-2758ecd8-85a1-11e7-8d72-ae9c99142dc7.png)

**Comment by yeboahnanaosei** [comment]
Hi Dan,
Which tool did you use to create this mockup. I will like to tinker with a few mockups.

**Comment by yeboahnanaosei** [comment]
What do you think of this? Each element in the status bar can be replaced with an icon. 

<img width="2021" alt="scratch_mockup_statusbar" src="https://user-images.githubusercontent.com/22800157/29518409-b5623990-8668-11e7-95f9-894a73b106a5.png">

**Comment by Nine-H** [comment]
I like dan's design more, but I want to know what happens when you half-screen it on a 1366*768 display.
