### ISSUE TITLE
We need an option "restore-tabs" like Files

### ISSUE THREAD

**Issue by artemanufrij** [elementary/scratch#162]
I think it would be helpful to have an option to start editor in "clear" mode

**Comment by danrabbit** [comment]
This was just recently killed. If you want to start up with nothing, I guess close all your documents before you close the window :p

**Comment by donadigo** [comment]
I disagree, 
> I guess close all your documents before you close the window

isn't really a solution to this issue, it's making the user waste his time on closing and also remembering that he has to close all those tabs before quitting.
