### ISSUE TITLE
Sane defaults for word completion

### ISSUE THREAD

**Issue by donadigo** [elementary/scratch#184]
Currently we have a word completion plugin in Scratch that's used for fetching words from the current document in order to show them in completion window.

The current minimum word length for the completion is 3 and the timeout for showing the completion window is 250 milliseconds. When the user is typing really fast, this window is almost never useful, since most words in programming have 6-10 character length with an exception for constants and the window pops up at the very end of typing the word. Add to that the 250ms timeout and your word will almost likely be already completed. I think based on my experience, most of the times I want to type the first, second letter and immediately get the words completion to pop up.

I suggest lowering those values to: 1-2 word length (preferably 1), and 0 miliseconds for the timeout to show the completion window.

**Comment by danrabbit** [comment]
I'd also like to propose setting `current_view.completion.show_headers = false;` since it seems like all that does is show the current file name

**Comment by donadigo** [comment]
Yes, that would be also sane.
