### ISSUE TITLE
Completion Suggestion is poorly formatted

### ISSUE THREAD

**Issue by OttoRobba** [elementary/scratch#205]
The removal of the header, as per pull https://github.com/elementary/scratch/pull/188, has broken how suggestions are displayed.

Without header:
![buggy_completion](https://user-images.githubusercontent.com/597287/29850336-33f32184-8d03-11e7-9234-5e712a08dbee.png)

With header:
![proper_completion](https://user-images.githubusercontent.com/597287/29850367-881300ea-8d03-11e7-9e68-eddc2e346af4.png)

**Comment by danrabbit** [comment]
Hmm, I can't confirm this. OP can you give some more information about your system? Are you using a custom stylesheet or fonts? Can you reproduce this issue with elementary OS default settings?

**Comment by OttoRobba** [comment]
This is odd. It seems to be working fine now - not sure if it was a problem on that build, maybe a leftover that was corrected by redoing DCMakeInstallPrefix. Closing it.
