### ISSUE TITLE
Don't complete brackets in front of letters

### ISSUE THREAD

**Issue by snowparrot** [elementary/scratch#215]
Like in Sublime Code /Scratch shouldnt complete brackets if cursor is left of letters and numbers.

**Comment by matzipan** [comment]
Does this behavior exist with pull request #203 ?

**Comment by snowparrot** [comment]
Neither #183 , #151 nor #31 includes my pull request. :-P

#203 is too heavy to include this feature now so I'm waiting until it is merged into master and code this feature.

**Comment by OttoRobba** [comment]
@snowparrot It would be trivial for me to include it in #203 if you want :)

**Comment by snowparrot** [comment]
sure but let me find out which char exactly.

**Comment by snowparrot** [comment]
@OttoRobba my exact proposal: Dont have brackets completion if there are alphanumerical chars next to the cursor. 
If there is e.g. a comma, or a semicolon you still have brackets completion.

**Comment by snowparrot** [comment]
@OttoRobba Please consider to add this feature after you solved all problems in the PR request.
