### ISSUE TITLE
Pressing ctrl-z clears the entire text view and saves

### ISSUE THREAD

**Issue by matzipan** [elementary/scratch#219]
Steps to reproduce:
1. Open any file
2. Press ctrl-z
3. The sourceview is emptied and the file is saved.

Marked as critical since it leads to dataloss

**Comment by artemanufrij** [comment]
I can't reproduce it

**Comment by jeremypw** [comment]
I cannot reproduce it. The nearest I can get is to start with loading and empty (saved) document, typing some stuff and pressing <Ctrl><Shift>O (revert).

**Comment by OttoRobba** [comment]
Cannot reproduce either. @matzipan Which plugins do you have currently activated?

**Comment by matzipan** [comment]
Hmmmm I can't reproduce anymore, it must be a bug from a branch I had built and installed (wrongly I did `cmake` without `CMAKE_INSTALL_PREFIX=/usr`, which meant when I did an `apt install --reinstall` I would still see the same behaviour).

Closing for now.
