### ISSUE TITLE
Thumbnailing files on MTP device fails and closes connection

### ISSUE THREAD

**Issue by jeremypw** [elementary/scratch#250]
If "show-remote-thumbnails" is turned on and an MTP device folder containing pictures is mounted, the thumbnails do not show and if hovered over the connection breaks and the device is unmounted.

See: https://bugs.launchpad.net/pantheon-files/+bug/1456470

**Comment by matzipan** [comment]
@jeremypw  you filed this under Scratch instead of Files.

**Comment by jeremypw** [comment]
OOPs, too many tqabs open ... thanks for spotting this.
