### ISSUE TITLE
Doesn't open anymore after load a heavy file

### ISSUE THREAD

**Issue by herlon214** [elementary/scratch#267]
Hi guys!

I opened a large text file with Scratch now it doesn't open anymore. Now I can't open any file with it, always crash when opening.
I think that it's restoring a previous session (maybe that I loaded the large text file).

Any workaround for this? 

Thanks in advance.

**Comment by tintou** [comment]
Sadly, you need to clear the values of Scratch's GSettings

**Comment by tintou** [comment]
open the dconf-editor and go to /org/pantheon/scratch/settings and remove the references to the file

**Comment by herlon214** [comment]
Thanks for the answer @tintou. It worked!
