### ISSUE TITLE
Change user-facing name to Code

### ISSUE THREAD

**Issue by cassidyjames** [elementary/scratch#59]
Scratch is already a thing on other platforms and is way more well-known, so it's a bit weird to have our editor named the same thing. Plus it doesn't do a great job communicating it's a code-writing app and not just a "scratch pad" for ideas.

"Code" is my proposal, but I'm open to whatever.

**Comment by cassidyjames** [comment]
Plus @danrabbit is making a sexy new code-focused icon, so I think that could work. :D

**Comment by cassidyjames** [comment]
...i.e. in the .desktop file

**Comment by danrabbit** [comment]
Working on this at https://github.com/elementary/scratch/tree/branded-icon

**Comment by Appeltabak** [comment]
I don't know if it's an issue, but Microsoft's (increasingly popular) code-writing app VS Code installs it's binary als `code`, so that would collide (?)

**Comment by danrabbit** [comment]
No, the binary would be RDNN'd as `io.elementary.code`
