### ISSUE TITLE
Failure to compile SourceTreePlugin.vala

### ISSUE THREAD

**Issue by jeremypw** [elementary/scratch#86]
Since Granite commit 0fa769629489bd74aa6b5ea633972c4749919cc3,  compiling Scratch fails with the error:

```
/scratch/plugins/source-tree/SourceTreePlugin.vala:222.13-222.30: error:
 The name `set_sort_func' does not exist in the context of `Granite.Widgets.SourceList'

            view.set_sort_func ((a, b) => {
            ^^^^^^^^^^^^^^^^^^
```

**Comment by danrabbit** [comment]
It looks like this method was deprecated in favor of `SourceListSortable.compare`

**Comment by jeremypw** [comment]
SourceTree no longer uses offending function and trunk compiles.
